#quarkus.application.name=myservice
#quarkus.otel.metrics.enabled=true
#quarkus.otel.metrics.exporter=logging
#quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
#quarkus.otel.exporter.otlp.protocol=http/protobuf
##quarkus.otel.exporter.otlp.metrics.headers=authorization=Bearer my_secret
#quarkus.otel.metric.export.interval=5000ms
#
##quarkus.observability.lgtm.otlp-protocol=grpc

#quarkus.management.enabled=true
#quarkus.otel.traces.suppress-non-application-uris=false

quarkus.micrometer.binder.vertx.enabled=true
quarkus.micrometer.binder.netty.enabled=true
quarkus.micrometer.binder.http-server.enabled=true
quarkus.micrometer.binder.http-client.enabled=true
quarkus.micrometer.binder.jvm=true

quarkus.datasource.jdbc.enable-metrics=true

#quarkus.class-loading.reloadable-artifacts=io.prometheus:simpleclient
