#quarkus.application.name=myservice
quarkus.otel.metrics.enabled=true
#quarkus.otel.metrics.exporter=logging
#quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
quarkus.otel.exporter.otlp.protocol=http/protobuf
#quarkus.otel.exporter.otlp.metrics.headers=authorization=Bearer my_secret
quarkus.otel.metric.export.interval=10000ms

#quarkus.management.enabled=true
#quarkus.otel.traces.suppress-non-application-uris=false

#quarkus.observability.lgtm.enabled=false

#quarkus.observability.enabled=false
#quarkus.observability.enabled-in-tests=true
#quarkus.observability.dev-resources=true

quarkus.otel.logs.enabled=true
