#quarkus.http.access-log.enabled=true
#quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %m "%{i,Referer}" "%{i,User-Agent}" "%{i,X-Request-Id}" "%{i,X-Organization-Id}" %D

#quarkus.micrometer.binder.http-server.enabled=true
#quarkus.micrometer.binder.http-client.enabled=true
#quarkus.micrometer.binder.jvm=true

quarkus.otel.metric.export.interval=1000ms

#quarkus.otel.metrics.enabled=true
#quarkus.otel.logs.enabled=true

#quarkus.http.access-log.enabled=true
#quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %m "%{i,Referer}" "%{i,User-Agent}" "%{i,X-Request-Id}" "%{i,X-Organization-Id}" %D

#quarkus.observability.lgtm.logging=ALL

#quarkus.observability.lgtm.grafana-port=3001
#quarkus.observability.lgtm.otel-grpc-port=5317
#quarkus.observability.lgtm.otel-http-port=5318