#quarkus.application.name=myservice
#quarkus.otel.metrics.enabled=true
##quarkus.otel.metrics.exporter=logging
##quarkus.otel.exporter.otlp.endpoint=http://localhost:4318
#quarkus.otel.exporter.otlp.protocol=http/protobuf
##quarkus.otel.exporter.otlp.metrics.headers=authorization=Bearer my_secret
#quarkus.otel.metric.export.interval=10000ms


quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %l %u %t "%r" %s %b %m "%{i,Referer}" "%{i,User-Agent}" "%{i,X-Request-Id}" "%{i,X-Organization-Id}" %D
#quarkus.http.access-log.base-file-name=project-name-log
#quarkus.http.access-log.log-directory=/var/log/
#quarkus.log.category."io.quarkus.http.access-log".level=INFO
quarkus.http.access-log.log-to-file=true